### ISSUE TITLE
Works perfect on Android but not on IOS.

### ISSUE THREAD

**Issue by KarHack** [dlutton/flutter_tts#21]
I followed the Example properly, and it works perfectly on android, but it just doesn't work on IOS. Please help. Thanks a ton.
It doesn't work on the IOS speaker nor the Headphones.

**Comment by IvanBean** [comment]
Similar issue here, clone the example and testing on real device iPhone 7 running iOS 12.1.2. Many languages shows duplicate item: [https://i.imgur.com/B69Cfgx.png](https://i.imgur.com/B69Cfgx.png), select the duplicated one leads to an error: [https://i.imgur.com/1ejQp7v.png](https://i.imgur.com/1ejQp7v.png). 

Other selectable language dosen't play sound when hit the button, tested on plugin version 0.1.2 and 0.2.0.

Android works well include the voices options which just added in 0.2.0.

Thanks for your effort, any reply will be appreciated.

**Comment by dlutton** [comment]
@KarHack @IvanBean can one of you test the latest 0.2.1 package I just published?  Thank you

**Comment by KarHack** [comment]
I just cleaned and checked 0.2.1 package, on Iphone 6s running iOS 12.1.2. It is still not working.
Thanks for your quick reply and effort, really great project.

**Comment by IvanBean** [comment]
Hi @dlutton 

Thanks for quick reply, the duplicate language is fixed now. 

About the voice, after some investigate I found one solution is add `AVFoundation` to `AppDelegare.swift` under ios/runner directory, full code:
```
import UIKit
import Flutter
import AVFoundation

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    do {
        try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
        do {
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            
        }
    } catch {
        
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
```
In this way the voice can play successfully, however, I'm a Android developer and new to Flutter so i don't know whether this is a correct approach. Thanks.

**Comment by dlutton** [comment]
Unfortunately i don't have a 6s phone to test it on @KarHack.  I did test a 6s emulator and it's working.  The voice is also working when I test on my physical device (iphone Xs).  Are there any error logs you can provide from your device?

**Comment by KarHack** [comment]
I cloned the project, and its working on the Iphone 6s iOS 12.1.2.
Probably I missed something when copying from the example. Thanks a ton.

**Comment by IvanBean** [comment]
@dlutton I copy `main.dart` from example too, not clone full project, sorry for misleading in my first comment. 
@KarHack maybe we meet the same problem that device can't play sounds without `AVAudioSessionCategoryPlayback`, you can try to edit `AppDelegare.swift` in my comment above as a temporary workaround if it works for you.

**Comment by KarHack** [comment]
@KarHack Will do that, next time. Thank you.
@dlutton Thanks a ton for the Library, I am Closing the Issue.

**Comment by dlutton** [comment]
@IvanBean I have merged the PR.   I'll have to refactor it once I upgrade the code to swift 4.2 since there appears to be [issues](https://stackoverflow.com/questions/51010390/avaudiosession-setcategory-swift-4-2-ios-12-play-sound-on-silent/52396244#52396244).  I'm hoping the ios/swift team can correct it without having to apply a bandaid.
