### ISSUE TITLE
calling await getVoices() after await setEngine() fails at random

### ISSUE THREAD

**Issue by mchlsndrn** [dlutton/flutter_tts#253]
Just like the title says, this behavior is inconsistent but tends to fail 50% of the time.
I'm currently only using this on Android.
As a workaround I wait a bit before making the 2nd call.

```
await flutterTts.setEngine(_selectedEngine);
await Future.delayed(Duration(milliseconds: 250)); // <-- WORKAROUND, uncomment to get an inconsistent fail
List<dynamic> availableVoices = await flutterTts.getVoices;
```

This is the error:

> I/TextToSpeech(15048): Sucessfully bound to com.google.android.tts
> I/TextToSpeech(15048): Connected to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
> I/TextToSpeech(15048): Set up connection to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
> W/TextToSpeech(15048): getVoices failed: TTS engine connection not fully set up
>

**Comment by vandir** [comment]
Same problem here? Are there news about this issue?

I looked at the source code of `setEngine`:
```dart
Future<dynamic> setEngine(String engine) => _channel.invokeMethod('setEngine', engine);
```

Shouldn't it be like the code below?

```dart
Future<dynamic> setEngine(String engine) => await _channel.invokeMethod('setEngine', engine);
```

This is what you do in other methods like `getLanguages`:
```dart
Future<dynamic> get getLanguages async {
  final languages = await _channel.invokeMethod('getLanguages');
  return languages;
}
```

**Comment by dlutton** [comment]
@vandir that looks like that could be an issue.  I'll get this fixed.  Thank you!

**Comment by dlutton** [comment]
fix has been merged in

**Comment by vandir** [comment]
Sorry @dlutton. The new version didn't fixed the issue. Maybe the problem is here:

```Kotlin
private fun setEngine(engine: String?, result: Result) {
    tts = TextToSpeech(context, onInitListener, engine)
    result.success(1)
}
```
In the code above the function returns right after initializing `TexToSpeech` without waiting the callback `onInitListener`. I think the function should return only after the callback is called. I paste below the definition of `TextToSpeech.OnInitListener` interface

`Interface definition of a callback to be invoked indicating the completion of the TextToSpeech engine initialization.`

Many thanks for your work.

**Comment by dlutton** [comment]
@vandir I was also receiving that `getVoices failed: TTS engine connection not fully set up`  message prior to the latest change and now I'm not.  I'll see if I can recreate it another way.

**Comment by dlutton** [comment]
@vandir I just realized that some engines may take longer to initialize than others depending on the device and engine, which is maybe why I'm not able to recreate it.

I published a change to a branch that should hopefully fix it.

When you get a chance, can you test out the branch?
You should be able to add it to your pubspec.yaml like this: 
```
  flutter_tts:
    git:
      url: git://github.com:dlutton/flutter_tts.git
      ref: android-set-engine-fix
```

If that works I'll publish the fix.

**Comment by vandir** [comment]
Many thanks for the quick fix! 

I confirm the message "TTS engine connection not fully set up" is gone and I can even see the following messages:

```
I/TextToSpeech(26066): Sucessfully bound to com.google.android.tts
I/TextToSpeech(26066): Connected to TTS engine
```

but the app still crash when doing setEngine and setLanguage twice. Below you can find the stack trace:

```
E/AndroidRuntime(25919): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25919): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(25919): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.setLanguage(FlutterTtsPlugin.kt:442)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.kt:357)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall$lambda-3(FlutterTtsPlugin.kt:257)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.$r8$lambda$ybPn496kgAkOZOG-C4sIr7lPTUY(Unknown Source:0)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$$ExternalSyntheticLambda4.run(Unknown Source:6)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onInitListener$lambda-2(FlutterTtsPlugin.kt:246)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.$r8$lambda$5_fJfpY3JF49b2AACIMNL5aTVqo(Unknown Source:0)
E/AndroidRuntime(25919): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$$ExternalSyntheticLambda0.onInit(Unknown Source:2)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$android-speech-tts-TextToSpeech(TextToSpeech.java:890)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech.-$$Nest$mdispatchOnInit(Unknown Source:0)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
E/AndroidRuntime(25919): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
E/AndroidRuntime(25919): 	at android.os.AsyncTask.finish(AsyncTask.java:771)
E/AndroidRuntime(25919): 	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
E/AndroidRuntime(25919): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
E/AndroidRuntime(25919): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25919): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(25919): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(25919): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(25919): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25919): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(25919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (25919): Sending signal. PID: 25919 SIG: 9
Lost connection to device.
```

Basically I have a settings screen with a button that the user could press when needs to test the TTS settings that he has changed.  This is the callback of the button:

```dart
if (_settings.ttsEngine != null) {
  await _tts.setEngine(_settings.ttsEngine!);

  // Workaround to fix bug: https://github.com/dlutton/flutter_tts/issues/253
  // await Future.delayed(const Duration(milliseconds: 250));
}

await _tts.setLanguage(_settings.ttsLanguage);
await _tts.setVolume(_settings.ttsVolume);

await _tts.speak('Test');
```

The problem does not happen when I enable the workaround (Future.delayed).

**Comment by dlutton** [comment]
@vandir okay great thanks for testing and the provided logs, I'll take a look into this issue.

**Comment by dlutton** [comment]
@vandir the fix for this is a bit complicated since we're suspending the calls while TTS is being initialized.  If that takes time, it can add a few calls which eventually runs and returns a reply after another has already fired thus displaying the error message you see.  As a work around until I can solve for that, I added a call back for when TTS is initialized to the same branch you're testing with.   Please test when you get a chance
```
if (isAndroid) {
      flutterTts.setInitHandler(() {
        setState(() {
          print("TTS Initialized");
          ttsState = TtsState.initialized;
        });
      });
    }
```

You can use this when you call setEngine so you know when it's completed and then you can continue making any calls to the TTS engine.  Let me know if this works for you.

**Comment by vandir** [comment]
I'm now using the code below:

```dart
if (_settings.ttsEngine != null) {
  _tts.setInitHandler(() async {
    await _tts.setLanguage(_settings.ttsLanguage);
    await _tts.setVolume(_settings.ttsVolume);
  });

  await _tts.setEngine(_settings.Test!);
}
```

but the problem persists. The first time it just works without errors, the second time I press the button (even after seconds) it crashes. If you want I can create a minimal example. I'm using the emulator "sdk gphone64 x86 64 (mobile) • android-x64    • Android 13 (API 33)".

**Comment by dlutton** [comment]
@vandir great and thanks for testing, I'll commit the code to master and publish a new release.

**Comment by vandir** [comment]
I saw your package update (3.6.1) and I can confirm it works but I have a tip for a cleaner solution.

If you want to trasparently handle this issue, maybe you can use a `Completer` object in `setEngine` function, something like code below:

```dart
Future<void> setEngine(String engine) async {
    final initCompleter = Completer<void>();
    _setInitHandler(() => initCompleter.complete());
    await _channel.invokeMethod('setEngine', engine);
    await initCompleter.future;
}
```
Then you can optionally hide again the new API and make `setInitHandler` private.

In this way, the users can safely call any other methods after `await setEngine(...)`, because the initialization is always completed (thanks to the line `await initCompleter.future`). 

In the current version (3.6.1), using or not the `await` keyword doesn't seem to make some difference and this is a "problem" because the users when call and `await` a method expect that method it was really completed.

**Comment by dlutton** [comment]
@vandir that's a great solution, I'll implement this next.  I agree that the `await` doesn't make a difference here because technically calling setEngine on the Android side is completed, however the `TextToSpeech.OnInitListener` callback isn't.

**Comment by dlutton** [comment]
@vandir when you get a moment, can you test out the branch android-init-fix, I'll publish the fix once confirmed.  Thanks again for helping test as I'm unable to recreate with the Pixel 5 device I have.  I kept the setInitHandler public so that it can be used when FlutterTts is instantiated since that is also instantiating Android's TextToSpeech which includes the Google TTS Engine by default which in turn invokes TextToSpeech.OnInitListener.

**Comment by vandir** [comment]
I've just tested the new branch and I can confirm it works! Thanks again for your efforts!

**Comment by vandir** [comment]
Sorry for opening this again, but I've found a bug with the code below:

```dart
final tts = FlutterTts();
await tts.setEngine('com.google.android.gm');
await tts.setEngine('com.google.android.gm');
await tts.setEngine('com.google.android.gm');
```

I've locally cloned the project and I've found the root cause. In the next days I will make a pull request about that.

Please also consider that `initHandler` is modified everytime `setEngine` is called, overwriting what the user has been set before. This is the reason why I made setInitHandler private in the example code in one of my previous messages.

**Comment by dlutton** [comment]
@vandir sounds good, look forward to seeing the pull request.
